#!/bin/bash
# Stub variables for ShellCheck static analysis only.

MEMPOOL_BASE_DIR="/opt/mempool"
MEMPOOL_NETWORKS="mainnet,signet"
ENABLE_SSL=false
DOMAIN_MAINNET=""
DOMAIN_SIGNET=""
ENABLE_UFW=true
USE_EXTERNAL_BITCOIND=false
BITCOIND_RPC_HOST="bitcoind"
BITCOIND_RPC_PORT=8332
BITCOIND_RPC_USER="mempool"
BITCOIND_RPC_PASS="mempool"
MONITORING_ENABLED=true
MAINNET_WEB_PORT=8080
MAINNET_API_PORT=8999
MAINNET_BIND_ADDRESS=""
SIGNET_WEB_PORT=8081
SIGNET_API_PORT=8998
SIGNET_BIND_ADDRESS=""
DB_USER="mempool"
DB_PASSWORD="mempool"
DB_NAME="mempool"
